### ISSUE TITLE
Introduce validators into quintessence

### ISSUE THREAD

**Issue by MarkOates** [MarkOates/blast#38]
in quintessence:
```
- validate
  - class: VectorValidator<std::string>
    init_with: '{ "who", "ha" }'
    validate_with:
      - contains(3)
      - min_token_count(2)
      - not_empty()
```

would produce:
```
{
   VectorValidator<std::string> validator({ "who", "ha" });
   std::vector<std::string> all_validator_errors;

   std::vector<std::string> validation_1 = validator.contains(3);
   all_validator_errors(all_validator_errors.end(), validation_1.begin(), validation_1.end());

   std::vector<std::string> validation_2 = validator.min_token_count(2);
   all_validator_errors(all_validator_errors.end(), validation_2.begin(), validation_2.end());

   std::vector<std::string> validation_3 = validator.not_empty();
   all_validator_errors(all_validator_errors.end(), validation_3.begin(), validation_3.end());

   if (!all_validator_errors.empty())
   {
      std::stringstream error_message;
      error_message << "ClassName::method: error: Following validations failed: ";
      ... list out all_validator_errors ...
      throw std::runtime_error(error_message);
   }
}
```

**Comment by MarkOates** [comment]
Most importantly the validator class is designed to have very user-friendly error messages that include the the data that didn't match validation.

**Comment by MarkOates** [comment]
Also consider introducing custom quintessence specifications so an end user could add in the "validate" element in their own projects without it having to become a major part of the standard quintessence schema.

**Comment by MarkOates** [comment]
You could have a standard validator with functions and remove the need for defining a class. For example:

```
validate:
  - not_nullptr(a_pointer)
  - vector_contains(tokens, "who")
  - min_token_count(tokens, 2)
  - tokens_not_empty(tokens)
```

A class would be implicitly included:

`class StandardValicator` that has the methods `std::vector<std::string> vector_contains(...)` ..., etc.

You may need to validate in stages

```
validate_in_groups:
  - validations:
     - not_nullptr(a_pointer)
  - validations:
    - vector_contains(tokens, "who")
    - min_token_count(tokens, 2)
    - tokens_not_empty(tokens)
```
